<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1676790058700" clover="3.2.0">
  <project timestamp="1676790058700" name="All files">
    <metrics statements="25" coveredstatements="25" conditionals="15" coveredconditionals="14" methods="5" coveredmethods="5" elements="45" coveredelements="44" complexity="0" loc="25" ncloc="25" packages="2" files="5" classes="5"/>
    <package name="Commons.exceptions">
      <metrics statements="18" coveredstatements="18" conditionals="3" coveredconditionals="3" methods="4" coveredmethods="4"/>
      <file name="AuthenticationError.js" path="/home/arya/Developments/Nodejs/auth-api/src/Commons/exceptions/AuthenticationError.js">
        <metrics statements="4" coveredstatements="4" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="1"/>
        <line num="1" count="1" type="stmt"/>
        <line num="5" count="1" type="stmt"/>
        <line num="6" count="1" type="stmt"/>
        <line num="10" count="1" type="stmt"/>
      </file>
      <file name="ClientError.js" path="/home/arya/Developments/Nodejs/auth-api/src/Commons/exceptions/ClientError.js">
        <metrics statements="6" coveredstatements="6" conditionals="3" coveredconditionals="3" methods="1" coveredmethods="1"/>
        <line num="3" count="4" type="stmt"/>
        <line num="5" count="4" type="cond" truecount="2" falsecount="0"/>
        <line num="6" count="1" type="stmt"/>
        <line num="9" count="3" type="stmt"/>
        <line num="10" count="3" type="stmt"/>
        <line num="14" count="4" type="stmt"/>
      </file>
      <file name="InvariantError.js" path="/home/arya/Developments/Nodejs/auth-api/src/Commons/exceptions/InvariantError.js">
        <metrics statements="4" coveredstatements="4" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="1"/>
        <line num="1" count="1" type="stmt"/>
        <line num="5" count="1" type="stmt"/>
        <line num="6" count="1" type="stmt"/>
        <line num="10" count="1" type="stmt"/>
      </file>
      <file name="NotFoundError.js" path="/home/arya/Developments/Nodejs/auth-api/src/Commons/exceptions/NotFoundError.js">
        <metrics statements="4" coveredstatements="4" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="1"/>
        <line num="1" count="1" type="stmt"/>
        <line num="5" count="1" type="stmt"/>
        <line num="6" count="1" type="stmt"/>
        <line num="10" count="1" type="stmt"/>
      </file>
    </package>
    <package name="Domains.users.entities">
      <metrics statements="7" coveredstatements="7" conditionals="12" coveredconditionals="11" methods="1" coveredmethods="1"/>
      <file name="RegisterUser.js" path="/home/arya/Developments/Nodejs/auth-api/src/Domains/users/entities/RegisterUser.js">
        <metrics statements="7" coveredstatements="7" conditionals="12" coveredconditionals="11" methods="1" coveredmethods="1"/>
        <line num="3" count="3" type="cond" truecount="5" falsecount="0"/>
        <line num="4" count="1" type="stmt"/>
        <line num="6" count="2" type="cond" truecount="5" falsecount="0"/>
        <line num="7" count="1" type="stmt"/>
        <line num="9" count="1" type="cond" truecount="1" falsecount="1"/>
        <line num="10" count="1" type="stmt"/>
        <line num="14" count="1" type="stmt"/>
      </file>
    </package>
  </project>
</coverage>
